### PR TITLE
Changed path dependencies to use pub.dev and API compatible version ranges

### LINKED ISSUE #54: Change all relative dependencies to use pub.dev (as opposed to path or git dependencies)

### PR DESCRIPTION
**Pull request by ricardoboss**
Also updated some (dev) dependencies that where not aligned with the other packages.

Fixes #54

### CODE REVIEW

**Comment by ricardoboss** [comment]
@baywet the CI failing is expected since the packages now depend on the version that is available on pub.dev. Since we haven't published any packages yet, the CI cannot get them.

This should be resolved once we publish the first version.

**Comment by baywet** [comment]
Thank you for the additional information.

Is there no way to setup a fallback? I'm worried about a few things:
- depending on how much time we take for the initial publish, it might mask broken additional changes.
- contributors will have to change those back when working on changes across multiple projects.
- publishing might initially fail because of the lack of a specific version, also the workflow will have to publish in the order of the dependency tree.

**Comment by ricardoboss** [comment]
AFAIK there is kind of fallback behaviour for pub dependencies. I have an idea how to work around this though:

1. replace all dependencies with git dependencies (i.e. cherry pick this commit: https://github.com/kiota-community/dart_kiota/commit/c1465a669eefa1b7a5a8b12f48e5f76e292c0e14)
2. replace all those dependencies with a specific version when publishing

This would allow us to ensure compatibility with the `main` branch while developing PRs but also requires more attention when publishing versions (pub.dev doesn't allow path or git dependencies in published packages).

**Comment by ricardoboss** [comment]
We could also temporarily use `dependency_overrides` to change the dependencies to path/git until the first version is published https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by ricardoboss** [comment]
Closing in favor of #60

**Pull request closed without merging**
